name: pull_request

on:
  push:
    branches:
      - 'master'
  pull_request: {}

jobs:
  build:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install just
        uses: extractions/setup-just@v2
      - name: Test
        run: just test
      - name: Check generated
        run: just check-generated
      - name: Release snapshot
        run: |
          API_VERSION="$(go run . describe 2>/dev/null | jq -r .api_version)"
          export API_VERSION
          go tool goreleaser build --snapshot --single-target --clean
