name: pull_request

on:
  push:
    branches:
    - 'master'
  pull_request: {}
  release:
    types: [published]

jobs:
  build:
    if: ${{! github.event.release.tag_name}}
    name: build-works
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Install just
      uses: extractions/setup-just@v2
    - name: Acceptance test
      run: |
        curl -sSL -O https://releases.hashicorp.com/packer/1.11.0/packer_1.11.0_linux_amd64.zip
        unzip packer_1.11.0_linux_amd64.zip
        mv packer /usr/local/bin/packer
        rm packer_1.11.0_linux_amd64.zip
        just install-local
        just testacc-sudo
    - name: Failed acceptance
      if: ${{ failure() }}
      run: |
        echo pkg/builder/packer_log_image-arm-builder_basic_test.txt
        cat pkg/builder/packer_log_image-arm-builder_basic_test.txt
    - name: Release snapshot
      run: |
        just release-snapshot
  release:
    name: release
    runs-on: ubuntu-latest
    if: github.event.release.tag_name
    env:
      TAGGED_VERSION: ${{github.event.release.tag_name}}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Install just
      uses: extractions/setup-just@v2
    - name: Go releaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        just release
